name: Update Cloudlafre IP list

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-cloudflare-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.14"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests~=2.0 pytz~=2024.1
      - name: Generate Cloudflare IP list
        run: |
          python cloudflare_ips.py
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          timezone: Europe/Warsaw
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Cloudflare IP list ${{ steps.current-time.outputs.formattedTime }}"
          branch: main
          commit_user_name: GitHub Actions
          commit_user_email: noreply@github.actions.bot
          commit_author: GitHub Actions <noreply@github.actions.bot>
